class A extends RuntimeException {
  //@ public normal_behavior
  //@ ensures \result == true;
  public boolean equals(Object obj);

  //@ public normal_behavior
  //@ ensures \result == this.hashCode();
  public int hashCode();

  //@ public normal_behavior
  //@ ensures \result == this.toString();
  public String toString();
}

class B extends A {
  //@ public normal_behavior
  //@ ensures \result == true;
  public boolean equals(Object obj);

  //@ public normal_behavior
  //@ ensures \result == this.hashCode();
  public int hashCode();

  //@ public normal_behavior
  //@ ensures \result == this.toString();
  public String toString();
}

public class exception18 {
  //@ public normal_behavior
  //@ ensures \result == true;
  public static boolean \invariantMethod();

  //@ public normal_behavior
  //@ ensures \result == true;
  public static boolean \invariantMethod();

  //@ public normal_behavior
  //@ requires true;
  //@ ensures true;
  private static void foo() throws A;

  //@ public normal_behavior
  //@ requires \invariantMethod();
  //@ ensures \invariantMethod();
  public static void main(String[] args) throws A;
}

